[package]
name = "vpo-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sound-engine = { path = "./sound-engine" }
node-engine = { path = "./node-engine" }
ipc = { path = "./ipc" }
async-std = "1.10.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
routerify = "3.0.0"
hyper = "0.14.18"
strum = "0.24.0"
strum_macros = "0.24"
rhai = { version = "1.7.0", features = ["f32_float", "only_i32"] }

[profile.release-x86_64-pc-windows-gnu]
inherits = "release"
opt-level = 3

[profile.release-x86_64-unknown-linux-gnu]
inherits = "release"
opt-level = 3

[profile.debug-release]
inherits = "dev"
opt-level = 3
debug = 2


[workspace]

members = [
    "sound-engine",
    "node-engine",
    "ipc"
]